source "https://rubygems.org"

gem "jekyll", "~> 4.3"
gem "just-the-docs", "0.8.2"
gem "sass-embedded", "~> 1.69.5"
gem "bigdecimal"

group :jekyll_plugins do
  gem "jekyll-seo-tag"
  gem "jekyll-github-metadata"
end

# Platform-specific gems
platforms :mingw, :x64_mingw, :mswin, :jruby do
  gem "tzinfo", ">= 1", "< 3"
  gem "tzinfo-data"
end

gem "wdm", "~> 0.1", :platforms => [:mingw, :x64_mingw, :mswin]
gem "http_parser.rb", "~> 0.6.0", :platforms => [:jruby]

# Performance-booster
gem "webrick"
