# SPDX-FileCopyrightText:  Copyright 2025 Anthony Green
# SPDX-License-Identifier: MIT
#
# Project:  x2ansible
# File:     build.yaml
# Date:     2025-06-23
#
# ==============================================================================

name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        id: setup
        with:
          python-version: '3.12'
          cache: 'pip'
          cache-dependency-path: requirements.txt

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install pylint
        run: pip install pylint

      - name: Analyse code with pylint
        run: pylint $(git ls-files '*.py') || true

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2.1.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}

      - name: Build and push container image
        uses: docker/build-push-action@v4.0.0
        with:
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/x2ansible:latest
